project_web/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import include, path
import web_story6.urls as web_story6
import subscribee.urls as subscribee

urlpatterns = [
    path('admin/', admin.site.urls),
	url(r'^web_story6', include(web_story6, namespace = 'web_story6')),	url(r'^subscribe', include(subscribee))
]

subscribee/urls.py
from django.conf.urls import url
from .views import subscribe, user_validate, profile, myajaxview
from django.views.generic.base import RedirectView

urlpatterns = [
	url('sub/', subscribe, name = 'subscribe'),
	url('see-profile/', profile, name = 'profile'),
    url('validate/', user_validate , name='validate_email'),
	url('data-view/', myajaxview , name='myajaxview')
]

web_story6/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView
from .views import lihat_profil, status, lihat_books, data_buku

#url for app
app_name = "web_story6"
urlpatterns = [
	url(r'^$', RedirectView.as_view(url = 'status/')),
	url(r'status/', status, name = 'status'),
	url(r'profile/', lihat_profil, name = 'lihat_profil'),
	url(r'books/', lihat_books, name = 'lihat_books'),
	url(r'data/', data_buku, name = 'data_buku'),
]

subscribee/models.py
from django.db import models

# models of regist subscriber
class RegisterSubscriber(models.Model):
    nama = models.CharField(max_length=30)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=30)

	

web_story6/models.py
from django.db import models
from django import forms
from django.utils import timezone
from datetime import datetime, date



class StatusModel (models.Model):
	status_message = models.CharField(max_length=200)
	created_date = models.DateTimeField(default=timezone.now)

subscribee/forms.py
from django import forms
from .models import RegisterSubscriber

# implement forms using ModelForm
class SubscriberForm(forms.ModelForm):
    class Meta:
        model = RegisterSubscriber
        fields = ['nama', 'email', 'password']
        widgets = {
            'nama': forms.TextInput(
                attrs={'class': 'form-control', 'id':'nama_form', 'placeholder': 'Name' , 'maxlength': 30}),

            'email': forms.TextInput(
                attrs={'type':'email','class': 'form-control', 'id':'email_form','placeholder': 'Email', 'maxlength': 30}),
            
            'password': forms.TextInput(
                attrs={ 'type':'password' ,'class': 'form-control', 'id':'password_form','placeholder': 'Password', 'maxlength': 30}),
        }

web_story6/forms.py
from django import forms

from django.forms import Form
from .models import StatusModel


class StatusForm(forms.Form):
	created_date = forms.DateTimeInput(attrs={'class': 'form-control'})
	error_messages = {'required': 'This field is required.',}
	description_attrs = {
        'type': 'text',
        'cols': 75,
        'rows': 6,
        'class': 'todo-form-textarea',
        'placeholder':'Status...'
    }
	status_message = forms.CharField(label='', required=True, widget=forms.Textarea(attrs=description_attrs))
	
	class Meta:
		model = StatusModel
		fields = ['status_message','created_date']

subscribee/views.py
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse, HttpResponse
from .forms import SubscriberForm
from .models import RegisterSubscriber
import requests, json, re

# function POST request subscriber
@csrf_exempt
def subscribe(request):
    get_user_acccount = RegisterSubscriber.objects.all()
    if request.method == "POST":
        form_value = SubscriberForm(request.POST or None)
        nama = request.POST['nama']
        email = request.POST['email']
        password = request.POST['password']
        user_filter_email = RegisterSubscriber.objects.filter(email=email)
        if (len(user_filter_email) > 0):
            response_message = 'Use another email please!~'
        else:
            create_user = RegisterSubscriber(email=email, nama=nama, password=password)
            create_user.save()
    else:
        form_value = SubscriberForm()

    return render(request, 'subscribe.html', {'form': form_value, 'data':get_user_acccount})


def profile(request):
    return render(request, 'see-profile.html')
	

@csrf_exempt
def user_validate(request):
    
    nama_validate_check = False
    email_validate_check = False
    password_validate_check = False
    
    if request.method == "POST":
        nama = request.POST['nama']
        email = request.POST['email']
        password = request.POST['password']

        # nama harus >= 4 dan <=50        
        if 4 <= len(nama) <= 50:
            nama_validate_check = True

        # email harus dicek
        if len(email) >= 8:
            email_validate_check = bool(re.match("^.+@(\[?)[a-zA-Z0-9-.]+.([a-zA-Z]{2,3}|[0-9]{1,3})(]?)$", email))

        # password harus lebih dr 8 dan kurang dari 50
        if 8 <= len(password) <= 50:
            password_validate_check = True

        # pesan kalo nama gasesuai
        if not nama_validate_check:
            return HttpResponse(json.dumps({'message': 'Name min 4 and max 30!'}), content_type="application/json")

        # pesan kalo email gasesuai
        if not email_validate_check:
            return HttpResponse(json.dumps({'message': 'Make sure input the right email yo!'}), content_type="application/json")

        # pesan kalo email udh dipake
        user_filter_email = RegisterSubscriber.objects.filter(email=email)
        if len(user_filter_email) > 0:
            return HttpResponse(json.dumps({'message': 'Email already registered! Use another yeah:('}), content_type="application/json")

        # kalo pas gasesuai
        if not password_validate_check:
            return HttpResponse(json.dumps({'message': 'Pass must contain at least 8 characters'}), content_type="application/json")
        return HttpResponse(json.dumps({'message': 'All fields are valid'}), content_type="application/json")

    else:
        return HttpResponse(json.dumps({'message': "ANY BUG BUG BUG YUHUU! TryAgain tommorow. I'm tired"}), content_type="application/json")

def myajaxview(request):
    report = []   
    query = RegisterSubscriber.objects.all()
    for q in query:
        report.append(q.nome_struttura)
        json = json.dumps(report)
    return HttpResponse(json, content_type='application/json')

web_story6/views.py
from django.urls import reverse
from .forms import StatusForm
from .models import StatusModel
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render


from django.shortcuts import render, render_to_response
from django.template import RequestContext, loader
import urllib.request, json, requests

# Create your views here.

response = {}
def lihat_profil(request):
	return render(request, 'profile.html')


def lihat_books(request):
	return render(request, 'books.html')

def data_buku(request):
	
	value = requests.get("https://www.googleapis.com/books/v1/volumes?q=computer");
	return HttpResponse(value, content_type='application/json')	

def status(request):
	todo = StatusModel.objects.all()
	if(request.method == 'POST'):
		form = StatusForm(request.POST or None)
		if(form.is_valid()):
			response['status_message'] = request.POST['status_message'];
			stat = StatusModel(status_message=response['status_message'])
			stat.save()
			return HttpResponseRedirect('/web_story6/status/')
	else:
		form = StatusForm()
	return render(request, 'simple_web_status.html',{'todo':todo, 'form':form})

subscribee/templates/data-subs.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE HTML>
<html>
	<head>
		<title> Greetings! </title>
		<link rel="shortcut icon" href="https://lh3.google.com/u/0/d/1UPkkvnFXnuDDODqu4HCWYPCQsRAsZvxu=w1366-h657-iv1">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script type="text/javascript">
		$(window).load(function() {
			$(".loader").fadeOut(1000);
		});
	</script>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'stylee.css' %}">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	</head>
	
	<body>
		
		<div class="loader"></div>
       
    </div>

		
	</body>
</html>

subscribee/templates/see-profile.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE HTML>
<html>
	<head>
		<title> Greetings! </title>
		<link rel="shortcut icon" href="https://lh3.google.com/u/0/d/1UPkkvnFXnuDDODqu4HCWYPCQsRAsZvxu=w1366-h657-iv1">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script type="text/javascript">
		$(window).load(function() {
			$(".loader").fadeOut(1000);
		});
	</script>
	<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'stylee.css' %}">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	</head>
	
	<body>
		
		<div class="loader"></div>
		
		<button onclick="location.href='/subscribe/sub'"  class="buttonnn" type="button">Subscribe</button>
		<center style="margin-top:-80px">
			<img src = "https://lh3.google.com/u/0/d/1gG-S2-qZfDb-pvNrZVAaF11_RKfXfLw3=w1366-h657-iv1" style="border-radius:50%;width:400px; height: 400px;">
			<p class="nama">Angginistanti Fairuz Hanun</p>
			<p class="parr">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras vel vestibulum tellus. Proin non pretium felis, sit amet sollicitudin dolor. Donec tempus commodo massa sollicitudin placerat. In eu placerat ipsum. Duis blandit accumsan eros, in egestas ex ultricies et. Vestibulum et nibh non dolor auctor pharetra nec id ipsum. Duis id tellus vel dolor consequat dignissim tincidunt vel erat.

				Suspendisse ultricies, erat quis feugiat pretium, eros lorem lacinia justo, vel euismod nibh enim rutrum tellus. Suspendisse ut tortor finibus, euismod tortor quis, commodo ipsum. Vestibulum at mollis purus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur at mi erat. Integer vel tempus nisl. Sed condimentum aliquet varius. Morbi dignissim velit mi, eget maximus odio interdum quis.

				Aliquam ac orci nec ipsum congue convallis. Sed sapien neque, varius ut tortor quis, aliquet cursus tortor. Aenean dapibus, quam eu porttitor blandit, augue tellus congue quam, sed consequat magna arcu sit amet leo. Ut purus nibh, consequat sed eros vitae, rhoncus posuere purus. Fusce ultricies turpis vel sagittis ultricies. Praesent nec egestas dolor, et ullamcorper lectus. Donec quis nisi et diam egestas posuere. Vestibulum interdum sapien non egestas porttitor. Cras libero odio, placerat non molestie placerat, maximus ut dolor. Quisque eu quam nec sem vulputate lobortis. Vivamus diam nisi, ornare sed eros in, lacinia tincidunt mauris. Nam nibh mi, pharetra at dapibus a, rutrum vel metus. Morbi ultricies dui ac turpis pretium tempor. Sed et maximus tortor. Aenean rhoncus aliquet efficitur.			</p>
		</center>
		
	</body>
</html>

subscribee/templates/subscribe.html
{% load static %}
<html>
<head>
	<title> Greetings! </title>
	<link rel="shortcut icon" href="https://lh3.google.com/u/0/d/1UPkkvnFXnuDDODqu4HCWYPCQsRAsZvxu=w1366-h657-iv1">
    <script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="{% static 'ajax.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'website.css' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'stylee.css' %}">
	<script type="text/javascript">
		$(window).load(function() {
			$(".loader").fadeOut(1000);
		});
		
		
	
 </script>

	</script>
</head>

<body>
  <div class="container">
    <div class="mt-5">
        <center><p class="subss">Subscribe Form</p></center>
    </div>


    <div class="mt-3" id="msg_response"></div>
    <!-- create user response -->
        
    <form class="form-group" method="POST" id="subscribe_form" onsubmit="return false;">
        {% csrf_token %} 
        {% for field in form %}
        <div class="form-group haa">
            <b>{{ field.label }} : {{ field }}</b>
        </div>
        {% endfor %}

        <div class="mt-4" id="msg_validate"></div>
      
      <div><center>
        <input id="subscribe_button" style="font-size:30px;font-family:'Handlee', cursive" type="submit" value="Subscribe" class="btn btn-warning" disabled onclick="subscribe()"/>
      </center></div>
    
    </form>
	
	<center><p class="subss">Subscriber List</p></center>
	
	<div class="main-div">
			<div class="container mx-auto d-block">
				{% if data %}
					<table class="table table-striped">
						<thead>
							<tr>
								<th style="font-size:20px;font-family:'Handlee',cursive;" >Name</th>
				<th style="font-size:20px;font-family:'Handlee',cursive" >Email</th>
				<th style="font-size:20px;font-family:'Handlee',cursive" >Delete Button</th
							</tr>
						</thead>
						<tbody>
							{% for todo in data %}
								<tr>
									<td scope="row" style="font-size:20px;font-family:'Handlee',cursive">{{ todo.nama }}</td>
									<td scope="row" style="font-size:20px;font-family:'Handlee',cursive">{{ todo.email }}</td>
									<td scope="row" style="font-size:20px;font-family:'Handlee',cursive"><button   type="button">Delete</button></td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				{% else %}
					<h1 class="text-main" style = "margin-left: 350px; margin-top: 200px;font-family: Garamond; font-size: 40px;">Tidak Ada Status</h1>
				{% endif %}
			</div>
	
	
  </div>
</body>
</html>

web_story6/templates/books.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE HTML>
<html>
	<head>
		<title> Greetings! </title>
		<link rel="shortcut icon" href="https://lh3.google.com/u/0/d/1UPkkvnFXnuDDODqu4HCWYPCQsRAsZvxu=w1366-h657-iv1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
		<script src="{% static 'js/script.js' %}"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
		<script type="text/javascript">
			$(window).load(function() {
				$(".loader").fadeOut(0);
			});
		</script>
		<style>
		.kata1{
			font-size: 50px;
		}
		</style>
	</head>
	
	<body style="background-color:#5B869B">
		<div class="loader"></div>
		<center>
			<h1  style="font:Impact; font-size:50px; margin-top:100px; color:white"><b> REKOMENDASI BUKU</b></h1>
			
			
			<div>
			<p class = "favLoc" style="font-size:30px;font:Impact"><b style="color:white;">GENRE :</b>
			<button id="button1" style="margin-top:10px; background-color:white" class="buttonnn buttons" value="medicine">Medicine</button>
			<button id="button1" style="margin-top:10px; background-color:white" class="buttonnn buttons" value="computer">Computer</button>
			</p>
			<p class = "favLoc" style="color:white;font-size:30px;font:Impact"><b>LIKES
				<input id = "counterButton" style="font-size:30px;color:#5B869B;background-color:white"class="btn btn-circle btn-xl" type="button" value="0" ></b>
			</p>
			</div>
			<div style="margin-top:10px">
				<div class="main-div">
					<div class="container mx-auto d-block">
						<table class="table table-bordered" style="background-color:white;" id ="table_book">
							<thead>
								<tr>	
									<th style="width: 20%">Cover</th>
									<th style="width: 30%">Title</th>
									<th style="width: 30%">Author</th>
									<th style="width: 20%">Publisher</th>
									<th>See Details</th>
									<th>Likes</th>
								</tr>
							</thead>
						</table>
					</div>
				</div>
			</div>
		</center>
		<footer class="page-footer font-small blue" style="background-color:white">
			<div class="footer-copyright text-center py-3" style="font-size:20px">© 2018 Copyright:
				<a href="web_story6/profile/"> Angginistanti Fairuz Hanun</a>
			</div>
		</footer>

	</body>
</html>

web_story6/templates/profile.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE HTML>
<html>
	<head>
		<title> Greetings! </title>
		<link rel="shortcut icon" href="https://lh3.google.com/u/0/d/1UPkkvnFXnuDDODqu4HCWYPCQsRAsZvxu=w1366-h657-iv1">
	</head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script type="text/javascript">
		$(window).load(function() {
			$(".loader").fadeOut(10);
		});
	</script>
	<body>
		<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
		<div class="loader"></div>
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
		<div class = "ColorText" >
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
		<script src="{% static 'js/script.js' %}"></script>
			<img src = "https://lh3.google.com/u/0/d/1gG-S2-qZfDb-pvNrZVAaF11_RKfXfLw3=w1366-h657-iv1" style="margin-top:50px; margin-left:150px;width:350px; height: 450px;">
			<div class="kata">
				<p style="font-size:50px; font-family: Garamond"> <em>Halooo! </em></p>
				<p >Angginistanti Fairuz Hanun</p>
				<p> Anggis - 19 tahun </p>
				<p> Lahir di Tanjung Redeb, 25 September 1999 </p>
				<p> Anak ke-2 dari 2 bersaudara </p>
				<p> Mahasiswi dari Program Studi Sistem Informasi, Fakultas Ilmu Komputer, Universitas Indonesia </p>
				<p> Memiliki hobi menulis, dan mendengar musik klasik </p>
				<button onclick="location.href='/web_story6/status/'"  class="buttonnn" type="button">Halaman Utama</button>
				<button onclick="location.href='/web_story6/books/'"  class="buttonnn" type="button"> Rekomendasi Buku</button>
				<button id = "apayaakepo" class="buttonnn" >Ubah Tema</button>
			</div>
		</div>
		
		<div id="main">
		<div class="accordion">
				<div class="accordion-title">
					<h4 class="secondary">Aktivitas Saat Ini</h4>
				</div>
				<div class="accordion-text">
					<p> Mengerjakan Story 8 PPW</p>
					<p> Mengerjakan TP 2 SDA</p>
					<p> Mengerjakan Adbis</p>
				</div>
			</div>
			<div class="accordion">
				<div class="accordion-title">
					<h4 class="secondary">Pengalaman Organisasi atau Kepanitiaan</h4>
				</div>
			<div class="accordion-text">
				<table>
					<tr>
						<td>2018 - kini </td>
						<td>Staff Dept Pengmas BEM Fasilkom UI 2018</td>
					</tr>
					<tr>
						<td>2018 - kini </td>
						<td>Staff Biro KKM FUKI 2018 </td>
					</tr>
					<tr>
						<td>2018 - kini</td>
						<td>Wakil Penanggung Jawab Bidang Acara SIWAK - NG 2018</td>
					</tr>
					<tr>
						<td>2013 - kini</td>
						<td>Staff Medis PMB 2018</td>
					</tr>
				</table>
			</div>
			</div>
			<div class="accordion">
				<div class="accordion-title">
					<h4 class="secondary">Prestasi</h4>
				</div>
				<div class="accordion-text">
					<p> Antologi Puisi : Sajakin Aja ke - 3 </p>
					<a href = "https://www.wattpad.com/story/72739872-world-of-words"> Penulis Dalam Wattpad </a>
				</div>
			</div>
		</div>
	</body>
</html>

web_story6/templates/simple_web_status.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE HTML>
<html>
	<head>
		<title> Greetings! </title>
		<link rel="shortcut icon" href="https://lh3.google.com/u/0/d/1UPkkvnFXnuDDODqu4HCWYPCQsRAsZvxu=w1366-h657-iv1">
	</head>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
	<script type="text/javascript">
		$(window).load(function() {
			$(".loader").fadeOut(10);
		});
	</script>
	<style>
	.greetings_layout{
		margin-top: 100px;  
		font: Garamond; 
		font-size : 40px;
		color: white;
	}
	
	.giving_layout{
		margin-top: 0px;  
		font: Garamond; 
		font-size : 35px;
		color: white;
	}
	
	.profil_layout{
		margin-top: 0px;  
		font: Garamond; 
		font-size : 35px;;
		border-radius: 5px;
		font-size: 30px;
	}
	
	
	
	
	</style>
	<body >
		<div class="loader"></div>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css">
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
		<center>
			<h1 class= "greetings_layout"> <em>Hello, Apa kabar? </em> </h1>
			<h2 class= "giving_layout"> <em>Masukan status:</em> </h2>
			<button onclick="location.href='/web_story6/profile/'"   class="profil_layout" type="button">Halaman Profil</button>
		
		{% block content %}
		<form id="form" method="POST" action="{% url 'web_story6:status' %}">
            {% csrf_token %}
            {{ form }}
            <br>
			<input id="submit" type="submit" class="btn btn-lg btn-block btn-info" style= "font-size: 22px; font: Garamond width:10px" value="Submit">
        </form>
		
		
		<div class="main-div">
			<div class="container mx-auto d-block">
				{% if todo %}
					<table class="table table-striped">
						<thead>
							<tr>
							  <th scope="col"> Status </th>
							  <th scope="col"> Waktu </th>
							</tr>
						</thead>
						<tbody>
							{% for data in todo %}
								<tr>
									<td scope="row">{{ data.status_message }}</td>
									<td scope="row">{{ data.created_date }}</td>
								</tr>
							{% endfor %}
						</tbody>
					</table>
				{% else %}
					<h1 class="text-main" style = "margin-left: 350px; margin-top: 200px;font-family: Garamond; font-size: 40px;">Tidak Ada Status</h1>
				{% endif %}
			</div>
		</div>
		</center>
	{% endblock content %}
	</body>
</html>